### ISSUE TITLE
data.retrospective fails

### ISSUE THREAD

**Issue by knicely** [geoglows/pygeoglows#42]
As of today (18 Oct. 2024), data.retrospective from the geoglows library no longer works. I attempted to get streamflow data, like I have many times before, and today it stopped working with the error code in the screencaps below. I'm inputting a single stream ID. This worked perfectly fine yesterday. As far as I can tell, there have been no updates or changes to geoglows, so I'm guessing that something geoglows uses has been changed. 

![image](https://github.com/user-attachments/assets/a909bde9-efd0-4ecf-a931-632de01bd1e2)

![image](https://github.com/user-attachments/assets/a7d08880-104d-4164-8407-98c0fcd629df)

**Comment by msouff** [comment]
Thank you @knicely 

We are aware of this issue and are in the process of solving it.

**Comment by knicely** [comment]
Just as an FYI, it seems like this issue is now resolved. 

-Knicely
